name: "Update Supabase Dataset"
on:
    schedule:
        - cron: "0 12 * * *"
    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install PNPM
              run: npm install -g pnpm

            - name: Sync node version and setup cache
              uses: actions/setup-node@v4
              with:
                  node-version: "lts/*"
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install

            - name: Update Supabase dataset
              run: pnpm update
              env:
                  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
                  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

